version: "3"

services:
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    build:
        context: ./nginx
        dockerfile: Dockerfile
    container_name: "${PROJECT_NAME}_nginx"
    ports:
      - '80:80' #thamelmart
      - '443:443' #thamelmart
      
    volumes:
      - ./projects:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ./nginx/log:/var/log/nginx
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      thamelmart:
        aliases:
          - scrapper.test
          - api.thamelmart.test
          - thamelmart.test
          - iptv.test
          - newstb.test
          - micromovies.test
    depends_on:
      - php

  php:
    container_name: "${PROJECT_NAME}_php"
    build: ./php
    # restart: unless-stopped
    environment:
      PHP_MEMORY_LIMIT: "${PHP_MEMORY_LIMIT}"
      COMPOSER_MEMORY_LIMIT: '-1'
      USER: "${USER}"
      UID: "${UID}"
    volumes:
      - ./projects/api.thamelmart.test:/var/www/api.thamelmart.test
      - ./projects/thamelmart:/var/www/thamelmart
    ports:
      - '9000:9000'
      - '9003:9003'
    networks:
      - thamelmart
    depends_on:
      - mysql
      - pma
      - redis

  mysql:
    container_name: "${PROJECT_NAME}_mysql"
    build: ./mysql
    volumes:
      - "~/.myproject/data/mysql:/var/lib/mysql"
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: ${TIMEZONE}
    networks:
      - thamelmart

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: "${PROJECT_NAME}_pma"
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8090:80"
    networks:
      - thamelmart

  redis:
    build: ./redis
    container_name: "${PROJECT_NAME}_redis"
    volumes:
     - "~/.myproject/data/redis:/data"
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - thamelmart
networks:
  thamelmart:
    driver: bridge
