version: "3"

services:
  scrapper:
    container_name: "${PROJECT_NAME}_scrapper"
    restart: always
    build: ./projects/fastApi # From Current directory!
    command: "/usr/local/bin/gunicorn --preload --reload -b 0.0.0.0:8000 -w 4 -k uvicorn.workers.UvicornWorker app.main:app --chdir=/var/www/fastApi"
    volumes:
      - "./projects:/var/www"
    environment:
      PYTHON UNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
      APP_NAME: "fast api"
      ADMIN_EMAIL: "gracysusant@gmail.com"
      DB_URL: "mysql+mysqlconnector://root:root@mysql:3306/fastapi"
      SCRAP_API_TOKEN: "dd424a4ae2c60473bb07132def3b89a1"
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - thamelmart

  mysql:
    container_name: "${PROJECT_NAME}_mysql"
    image: mysql:latest
    command: mysqld --authentication_policy=mysql_native_password
    volumes:
      - "~/.myproject/data/mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fastapi
    networks:
      - thamelmart

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: "kuber_pma"
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8200:80"
    networks:
      - thamelmart
  
networks:
  thamelmart:
    driver: bridge
  # volumes: