version: "3"

services:
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    build:
        context: ./nginx
        dockerfile: Dockerfile
    container_name: "${PROJECT_NAME}_nginx"
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
      - '446:446'
    volumes:
      - ./projects/api.thamelmart.test:/var/www/api.thamelmart.test
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ./nginx/log:/var/log/nginx
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      thamelmart:
        aliases:
          - scrapper.test
    depends_on:
      - php
      - scrapper
  ui:
    container_name: "${PROJECT_NAME}_ui"
    volumes:
      - ./projects/thamelui:/var/www/thamelui
    build: ./projects/thamelui
    ports:
      - '3000:3000'
    networks:
      - thamelmart
  php:
    container_name: "${PROJECT_NAME}_php"
    build: ./php
    restart: unless-stopped
    environment:
      PHP_MEMORY_LIMIT: "${PHP_MEMORY_LIMIT}"
      COMPOSER_MEMORY_LIMIT: '-1'
    volumes:
      - ./projects/api.thamelmart.test:/var/www/api.thamelmart.test
    ports:
      - '9000:9000'
    networks:
      - thamelmart
    depends_on:
      - mysql
      - scrapper
      - pma

  scrapper:
    container_name: "${PROJECT_NAME}_scrapper"
    restart: always
    build: ./projects/fastApi # From Current directory!
    command: "/usr/local/bin/gunicorn --preload --reload -b 0.0.0.0:8000 -w 10 -k uvicorn.workers.UvicornWorker app.main:app --chdir=/var/www/fastApi"
    volumes:
      - "./projects:/var/www"
    environment:
      PYTHON UNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
      APP_NAME: "fast api"
      ADMIN_EMAIL: "gracysusant@gmail.com"
      DB_URL: "mysql+mysqlconnector://root:root@mysql:3306/fastapi"
      SCRAP_API_TOKEN: "dd424a4ae2c60473bb07132def3b89a1"
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - thamelmart

  mysql:
    container_name: "${PROJECT_NAME}_mysql"
    build: ./mysql
    volumes:
      - "~/.myproject/data/mysql:/var/lib/mysql"
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: ${TIMEZONE}
    networks:
      - thamelmart

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: "kuber_pma"
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8200:80"
    networks:
      - thamelmart
networks:
  thamelmart:
    driver: bridge
  # volumes:
