version: "3"

services:

  nginx:
    image: "${PROJECT_NAME}/nginx:1.0"
    restart: unless-stopped
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: "${PROJECT_NAME}_nginx"
    ports:
      - '80:80' #thamelmart
      - '443:443' #thamelmar
    volumes:
      - ./projects/api.techbizz.test:/usr/app
      - ./nginx/log:/var/log/nginx
    networks:
      backend:
        aliases:
          - api.techbizz.test
      frontend:
        aliases:
          - admin.techbizz.test
          - store.techbizz.test
    depends_on:
      - api
      - admin
      - store

  admin:
    container_name: "${PROJECT_NAME}_admin"
    image: "${PROJECT_NAME}/admin:1.1"
    build:
      context: './projects/admin'
      dockerfile: 'Dockerfile.prod'
    restart: unless-stopped
    ports:
      - '3000:3000'
    networks:
      - frontend
      - backend

  store:
    container_name: "${PROJECT_NAME}_store"
    image: "${PROJECT_NAME}/store:1.1"
    build:
      context: ./projects/store-ui
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    ports:
      - '3001:3001'
    networks:
      - frontend
      - backend

  api:
    container_name: "${PROJECT_NAME}_api"
    image: "${PROJECT_NAME}/api:1.1"
    build:
      context: ./projects/api.techbizz.test
      dockerfile: "Dockerfile.prod"
    restart: unless-stopped
    user: "apache:apache"
    environment:
      PHP_MEMORY_LIMIT: "${PHP_MEMORY_LIMIT}"
      COMPOSER_MEMORY_LIMIT: '-1'
    # volumes:
    #   - ./projects/api.techbizz.test:/var/www/api.techbizz.test
    ports:
      - '9000:9000'
    networks:
      - backend
    depends_on:
      - mysql
      - pma
      - redis

  mysql:
    container_name: "${PROJECT_NAME}_mysql"
    image: "${PROJECT_NAME}/mysql:1.0"
    build: ./mysql
    volumes:
      - "persist-data:/var/lib/mysql"
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: ${TIMEZONE}
    networks:
      - backend

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: "${PROJECT_NAME}_pma"
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8090:80"
    networks:
      - backend

  redis:
    build: ./redis
    container_name: "${PROJECT_NAME}_redis"
    image: "${PROJECT_NAME}/redis:1.0"
    volumes:
      - "persist-data:/data"
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
volumes:
  persist-data:
