apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    tier: backend
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: backend
      app: nginx
  template:
    metadata:
      labels:
        tier: backend
        app: nginx
    spec:
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
      containers:
      - name: nginx
        imagePullPolicy: Always
        image: nginx:latest
        volumeMounts:
          - name: nginx-config
            subPath: nginx.conf
            mountPath: /etc/nginx/nginx.conf
          - name: nginx-config
            subPath: app.conf
            mountPath: /etc/nginx/sites-available/app.conf
        ports: 
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits: 
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels: 
    tier: backend
    app: nginx
spec:
  selector:
    tier: backend
    app: nginx
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 32380
  # - name: https
  #   port: 443
  #   protocol: TCP
  #   targetPort: 443
  #   nodePort: 32443
  type: LoadBalancer