apiVersion: apps/v1
kind: Deployment
metadata:
  name: pma-deployment
spec:
  selector:
    matchLabels:
      app: pma
  template:
    metadata:
      labels:
        app: pma
    spec:
      containers:
      - name: pma
        image: phpmyadmin/phpmyadmin
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8200

---
apiVersion: v1
kind: Service
metadata:
  name: pma
spec:
  selector:
    app: pma
  ports:  
  - port: 8200
    targetPort: 8200

