apiVersion: apps/v1
kind: Deployment
metadata:
  name: pma-deployment
spec:
  selector:
    matchLabels:
      app: pma
  template:
    metadata:
      labels:
        app: pma
    spec:
      containers:
      - name: pma
        image: phpmyadmin/phpmyadmin
        env:
          - name: PMA_HOST
            value: mysql-service
          - name: PMA_PORT
            value: "3306"
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secrets
                key: root-password
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: pma-service
spec:
  type: NodePort
  selector:
    app: pma
  ports:  
  - port: 80
    targetPort: 80

